name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cloud Build Lab Test
        id: cloudbuildlabtest
        uses: education/autograding-command-grader@v1
        with:
          test-name: Cloud Build Lab Test
          setup-command: npm install
          command: node cloud-test.js > test-result.log && grep '雲端環境運行成功' test-result.log
          timeout: 1
          max-score: 100
      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          CLOUDBUILDLABTEST_RESULTS: "${{steps.cloudbuildlabtest.outputs.result}}"
        with:
          runners: cloudbuildlabtest
